### ISSUE TITLE
Expand `dispatch` interface to support request other than http

### ISSUE THREAD

**Issue by weichensw** [omsmith/simple-path-router#1]
This helps when other protocol such as websocket to pass-by.

**Comment by omsmith** [comment]
Fixed by e3e73cd487874afa0440687ae21cbda6f94d533d and cb3d69465b7a7755cdaf44ef67b6bbd52875dad9.

Published as _1.1.0_

**Comment by weichensw** [comment]
Thanks @omsmith !
